name: guven_service
description: Network requests from Guven server
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  key_manager:
    path: ../key_manager
  logger: ^1.1.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
