name: scale_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  # guven_service:
  #   path: ../../guven_service
  scale_health_impl:
    path: ../scale_health_impl
  scale_hive_impl:
    path: ../scale_hive_impl

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
