name: scale_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  onedosehealth:
    path: ../../../../rbio

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
  build_runner: ^2.1.7
  freezed: ">=1.0.0 <1.1.1"
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
