name: onedosehealth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  app_settings: 4.1.0
  atom:
    git:
      url: https://jsck2wjl54wp5d65hbl32w6qpfxwae75bemnleehnhx23zqdxlra@guvenfuture.visualstudio.com/Atom/_git/Atom
      ref: master
  auto_size_text_pk: ^3.0.0
  built_value: ^8.0.5
  carousel_slider: ^4.0.0
  chopper: ^4.0.0-nullsafety.1
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  date_util: any
  device_info: ^2.0.2
  dio: ^4.0.0
  dropdown_banner: ^1.4.0
  expandable: ^5.0.1
  file_picker: ^3.0.1
  firebase: ^9.0.2
  firebase_analytics: ^8.3.3
  firebase_dynamic_links: ^2.0.10
  firebase_messaging: ^10.0.8
  flappy_search_bar: ^1.7.2
  flare_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_appavailability: null
  flutter_calendar_carousel: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_facebook_sdk: ^1.0.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_inner_drawer: ^1.0.0+1
  flutter_local_notifications: ^5.0.0+3
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: null
  flutter_material_pickers: ^2.1.1
  flutter_native_splash: ^1.2.1
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_it: ^7.2.0
  gradient_widgets: ^0.6.0
  hive: ^2.0.4
  http: ^0.13.2
  image_picker: ^0.7.4
  in_app_update: ^2.0.0
  intl: ^0.17.0
  intl_utils: ^2.2.0
  jitsi_meet: ^4.0.0
  jitsi_meet_platform_interface: ^2.0.0
  keyboard_avoider: ^0.1.0
  loading_animations: ^2.2.0
  logger: ^1.1.0
  numberpicker: ^2.1.1
  open_file: ^3.2.0
  package_info_plus: ^1.3.0
  path: null
  path_provider: ^2.0.1
  pdf: ^3.3.0
  percent_indicator: 2.1.6
  permission_handler: ^7.0.0
  photo_view: ^0.12.0
  progress_dialog: ^1.2.4
  provider: ^6.0.1
  pub_semver: ^2.0.0
  reorderables: ^0.4.1
  responsive_framework: ^0.1.5
  rxdart: ^0.26.0
  sentry_flutter: ^5.1.0
  shared_preferences: ^2.0.5
  simple_gesture_detector: ^0.2.0
  slugify: 1.0.0
  spring: ^2.0.2
  sqflite: null
  swipedetector: ^1.2.0
  syncfusion_flutter_pdfviewer: ^19.2.44-beta
  time: ^2.0.0
  turkish: ^0.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.3
  url_strategy: ^0.2.0
  vrouter: ^1.2.0+14
  webview_flutter: ^2.1.1
  wheel_chooser: ^0.1.1
  youtube_player_flutter: null
  youtube_player_iframe: null
  country_code_picker: ^2.0.2
  cloud_firestore: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.9
  built_value_generator: ^8.0.5
  chopper_generator: ^4.0.0-nullsafety.1
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - env/
    - assets/images/
    - assets/images/new/
    - assets/animations/
    - assets/sound/
    - assets/departments.json

  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansVariable_Roman.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/guven_app_logo.png"

flutter_intl:
  enabled: true
  class_name: LocaleProvider
  default_locale: en

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/guven_logo.png"
