name: onedosehealth
description: A new Flutter project.

publish_to: "none"

version: 1.0.11+22

environment:
  sdk: ">=2.15.0 <3.0.0"

dependency_overrides:
  flutter_reactive_ble:
    path: ./packages/flutter_reactive_ble
  reactive_ble_mobile:
    path: ./packages/reactive_ble_mobile
  keyboard_actions:
    path: ./packages/flutter_keyboard_actions

dependencies:
  animate_do: ^2.0.0
  animated_widgets: ^1.1.0
  app_settings: ^4.1.1
  atom:
    git:
      url: https://jsck2wjl54wp5d65hbl32w6qpfxwae75bemnleehnhx23zqdxlra@guvenfuture.visualstudio.com/Atom/_git/Atom
      ref: master
  auto_size_text_pk: ^3.0.0
  built_value: ^8.0.5
  cached_network_image: ^3.1.0+1
  carousel_slider: ^4.0.0
  cloud_firestore: 3.1.0
  connectivity_plus: ^2.2.0
  country_code_picker: ^2.0.2
  countup:
    git: https://github.com/alpceylan/flutter-countup.git
  cupertino_icons: ^1.0.4
  dart_date: ^1.1.0
  device_info_plus: ^3.2.1
  dio: ^4.0.4
  dropdown_banner: ^1.4.0
  encrypt: ^5.0.1
  expandable: ^5.0.1
  file_picker: ^3.0.0
  firebase: 9.0.2
  firebase_auth: 3.2.0
  firebase_core: 1.10.0
  firebase_dynamic_links: 3.0.1
  firebase_messaging: 11.2.4
  firebase_storage: 10.1.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_calendar_carousel: ^2.0.1
  flutter_datetime_picker:
    git: https://github.com/tushardubey121/flutter_datetime_picker.git
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.1.0
  flutter_local_notifications: 9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: null
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^1.3.1
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_reactive_ble: ^5.0.2
  flutter_share: ^2.0.0
  flutter_slidable: 0.6.0
  flutter_svg: ^0.23.0+1
  flutter_xlider: ^3.4.0
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  gradient_widgets: ^0.6.0
  grouped_list:
    path: ./packages/grouped_list
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  jitsi_meet_platform_interface: ^2.0.0
  jitsi_meet_wrapper: ^0.0.2
  keyboard_avoider:
    git:
      url: https://github.com/ryanheise/keyboard_avoider.git
      ref: fix/mounted-bug
  loading_animations: ^2.2.0
  logger: ^1.1.0
  numberpicker: ^2.1.1
  package_info_plus: ^1.3.0
  path: 1.8.0
  path_provider: ^2.0.7
  pdf: ^3.6.2
  percent_indicator: 2.1.6
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  progress_dialog: ^1.2.4
  progress_indicators: ^1.0.0
  provider: ^6.0.1
  pub_semver: ^2.0.0
  qr_code_scanner: ^0.6.1
  reorderables: ^0.4.1
  sentry_flutter: ^6.1.2
  share: ^2.0.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  simple_gesture_detector: ^0.2.0
  slugify: 1.0.0
  spring: ^2.0.2
  syncfusion_flutter_charts: ^19.3.54
  syncfusion_flutter_gauges: ^19.3.54
  syncfusion_flutter_pdfviewer: ^19.2.44-beta
  system_shortcuts: ^1.0.0
  table_calendar: ^3.0.3
  time: ^2.0.0
  timeago: ^3.1.0
  turkish: ^0.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.13
  url_strategy: ^0.2.0
  webview_flutter: ^2.3.1

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - env/
    - assets/images/
    - assets/images/bottom_navigation/
    - assets/animations/
    - assets/sound/
    - assets/departments.json
    - assets/pdf/

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro_Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/onedosehealth_logo-01.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  class_name: LocaleProvider
  default_locale: en

flutter_native_splash:
  color: "00A147"
  image: "assets/logo/splash_image.png"
