part of 'sp_manager.dart';

enum SharedPreferencesKeys {
  updateDialog,
  selectedLocale,
  didCompleteSurvey,
  loginUserName,
  loginPassword,
  profileImage,
  applicationConsentForm,
  jwtToken,
  patient,
  userAccount,
  canAccessHospitalOps,
  textScale,
  symtomAuthToken,
  pairedDevices,
  chatNotification,
  allUsers, // Home Widget List Tutuyor
  firstLaunch,
  isTwoFactorAuth,
  pairedDevicesV2,
  appDownload,
  hba1cList,
  medicineList,
  bloodGlucoseList,
  usedStripCount,
  consentId,
  isDefaultUser,
  theme,
}
