name: mi_scale
description: Get scale data from mi scale
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_reactive_ble: ^5.0.2
  scale_api:
    path: ../scale_api
dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
