name: scale_dependencies
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble:
    path: ../../flutter_reactive_ble
  freezed_annotation: ^2.0.3
  guven_service:
    path: ../../guven_service
  health:
    path: ../health
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.4
